// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: infoproto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from infoproto.proto</summary>
public static partial class InfoprotoReflection {

  #region Descriptor
  /// <summary>File descriptor for infoproto.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static InfoprotoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9pbmZvcHJvdG8ucHJvdG8aD2VudW1wcm90by5wcm90byJKCgxOQWNjb3Vu",
          "dEluZm8SEQoJYWNjb3VudElkGAEgASgDEhMKC2FjY291bnROYW1lGAIgASgJ",
          "EhIKCmFjY291bnRQd2QYAyABKAkiKwoITlZlY3RvcjMSCQoBeBgBIAEoBRIJ",
          "CgF5GAIgASgFEgkKAXoYAyABKAUi4QIKB05FbnRpdHkSDAoETmFtZRgBIAEo",
          "CRINCgVMZXZlbBgCIAEoBRIOCgZSb2xlSWQYAyABKAMSEwoLQmlnU2VydmVy",
          "SWQYBCABKAUSFQoNU21hbGxTZXJ2ZXJJZBgFIAEoBRIRCglBY2NvdW50aWQY",
          "BiABKAkSFwoEUmFjZRgHIAEoDjIJLkdhbWVSYWNlEiMKClByb2Zlc3Npb24Y",
          "CCABKA4yDy5HYW1lUHJvZmVzc2lvbhISCgpDdXJzY2VuZUlkGAkgASgFEhUK",
          "DUJlZm9yZVNjZW5lSWQYCiABKAUSFgoDUG9zGAsgASgLMgkuTlZlY3RvcjMS",
          "CgoCSHAYDCABKAUSCgoCTXAYDSABKAUSCwoDRXhwGA4gASgFEgwKBEdvbGQY",
          "DyABKAUSDwoHRGlhbW9uZBgQIAEoBRIWCgNEaXIYESABKAsyCS5OVmVjdG9y",
          "MxINCgVTcGVlZBgcIAEoBSI7CgVOSXRlbRIRCglpdGVtY2ZnaWQYASABKAMS",
          "DwoHaXRlbW51bRgCIAEoBRIOCgZpdGVtaWQYAyABKAViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::EnumprotoReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::NAccountInfo), global::NAccountInfo.Parser, new[]{ "AccountId", "AccountName", "AccountPwd" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::NVector3), global::NVector3.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::NEntity), global::NEntity.Parser, new[]{ "Name", "Level", "RoleId", "BigServerId", "SmallServerId", "Accountid", "Race", "Profession", "CursceneId", "BeforeSceneId", "Pos", "Hp", "Mp", "Exp", "Gold", "Diamond", "Dir", "Speed" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::NItem), global::NItem.Parser, new[]{ "Itemcfgid", "Itemnum", "Itemid" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
///账号信息
/// </summary>
public sealed partial class NAccountInfo : pb::IMessage<NAccountInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NAccountInfo> _parser = new pb::MessageParser<NAccountInfo>(() => new NAccountInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NAccountInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::InfoprotoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NAccountInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NAccountInfo(NAccountInfo other) : this() {
    accountId_ = other.accountId_;
    accountName_ = other.accountName_;
    accountPwd_ = other.accountPwd_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NAccountInfo Clone() {
    return new NAccountInfo(this);
  }

  /// <summary>Field number for the "accountId" field.</summary>
  public const int AccountIdFieldNumber = 1;
  private long accountId_;
  /// <summary>
  ///账号ID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long AccountId {
    get { return accountId_; }
    set {
      accountId_ = value;
    }
  }

  /// <summary>Field number for the "accountName" field.</summary>
  public const int AccountNameFieldNumber = 2;
  private string accountName_ = "";
  /// <summary>
  ///账号名
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AccountName {
    get { return accountName_; }
    set {
      accountName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "accountPwd" field.</summary>
  public const int AccountPwdFieldNumber = 3;
  private string accountPwd_ = "";
  /// <summary>
  ///账号密码
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AccountPwd {
    get { return accountPwd_; }
    set {
      accountPwd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NAccountInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NAccountInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (AccountId != other.AccountId) return false;
    if (AccountName != other.AccountName) return false;
    if (AccountPwd != other.AccountPwd) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (AccountId != 0L) hash ^= AccountId.GetHashCode();
    if (AccountName.Length != 0) hash ^= AccountName.GetHashCode();
    if (AccountPwd.Length != 0) hash ^= AccountPwd.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (AccountId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(AccountId);
    }
    if (AccountName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(AccountName);
    }
    if (AccountPwd.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(AccountPwd);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (AccountId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(AccountId);
    }
    if (AccountName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(AccountName);
    }
    if (AccountPwd.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(AccountPwd);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (AccountId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(AccountId);
    }
    if (AccountName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountName);
    }
    if (AccountPwd.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountPwd);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NAccountInfo other) {
    if (other == null) {
      return;
    }
    if (other.AccountId != 0L) {
      AccountId = other.AccountId;
    }
    if (other.AccountName.Length != 0) {
      AccountName = other.AccountName;
    }
    if (other.AccountPwd.Length != 0) {
      AccountPwd = other.AccountPwd;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          AccountId = input.ReadInt64();
          break;
        }
        case 18: {
          AccountName = input.ReadString();
          break;
        }
        case 26: {
          AccountPwd = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          AccountId = input.ReadInt64();
          break;
        }
        case 18: {
          AccountName = input.ReadString();
          break;
        }
        case 26: {
          AccountPwd = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class NVector3 : pb::IMessage<NVector3>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NVector3> _parser = new pb::MessageParser<NVector3>(() => new NVector3());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NVector3> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::InfoprotoReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NVector3() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NVector3(NVector3 other) : this() {
    x_ = other.x_;
    y_ = other.y_;
    z_ = other.z_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NVector3 Clone() {
    return new NVector3(this);
  }

  /// <summary>Field number for the "x" field.</summary>
  public const int XFieldNumber = 1;
  private int x_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int X {
    get { return x_; }
    set {
      x_ = value;
    }
  }

  /// <summary>Field number for the "y" field.</summary>
  public const int YFieldNumber = 2;
  private int y_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Y {
    get { return y_; }
    set {
      y_ = value;
    }
  }

  /// <summary>Field number for the "z" field.</summary>
  public const int ZFieldNumber = 3;
  private int z_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Z {
    get { return z_; }
    set {
      z_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NVector3);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NVector3 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (X != other.X) return false;
    if (Y != other.Y) return false;
    if (Z != other.Z) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (X != 0) hash ^= X.GetHashCode();
    if (Y != 0) hash ^= Y.GetHashCode();
    if (Z != 0) hash ^= Z.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (X != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(X);
    }
    if (Y != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Y);
    }
    if (Z != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Z);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (X != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(X);
    }
    if (Y != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Y);
    }
    if (Z != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Z);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (X != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(X);
    }
    if (Y != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Y);
    }
    if (Z != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Z);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NVector3 other) {
    if (other == null) {
      return;
    }
    if (other.X != 0) {
      X = other.X;
    }
    if (other.Y != 0) {
      Y = other.Y;
    }
    if (other.Z != 0) {
      Z = other.Z;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          X = input.ReadInt32();
          break;
        }
        case 16: {
          Y = input.ReadInt32();
          break;
        }
        case 24: {
          Z = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          X = input.ReadInt32();
          break;
        }
        case 16: {
          Y = input.ReadInt32();
          break;
        }
        case 24: {
          Z = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///角色信息
/// </summary>
public sealed partial class NEntity : pb::IMessage<NEntity>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NEntity> _parser = new pb::MessageParser<NEntity>(() => new NEntity());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NEntity> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::InfoprotoReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NEntity() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NEntity(NEntity other) : this() {
    name_ = other.name_;
    level_ = other.level_;
    roleId_ = other.roleId_;
    bigServerId_ = other.bigServerId_;
    smallServerId_ = other.smallServerId_;
    accountid_ = other.accountid_;
    race_ = other.race_;
    profession_ = other.profession_;
    cursceneId_ = other.cursceneId_;
    beforeSceneId_ = other.beforeSceneId_;
    pos_ = other.pos_ != null ? other.pos_.Clone() : null;
    hp_ = other.hp_;
    mp_ = other.mp_;
    exp_ = other.exp_;
    gold_ = other.gold_;
    diamond_ = other.diamond_;
    dir_ = other.dir_ != null ? other.dir_.Clone() : null;
    speed_ = other.speed_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NEntity Clone() {
    return new NEntity(this);
  }

  /// <summary>Field number for the "Name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  /// <summary>
  ///名字
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Level" field.</summary>
  public const int LevelFieldNumber = 2;
  private int level_;
  /// <summary>
  ///等级
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Level {
    get { return level_; }
    set {
      level_ = value;
    }
  }

  /// <summary>Field number for the "RoleId" field.</summary>
  public const int RoleIdFieldNumber = 3;
  private long roleId_;
  /// <summary>
  ///角色id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long RoleId {
    get { return roleId_; }
    set {
      roleId_ = value;
    }
  }

  /// <summary>Field number for the "BigServerId" field.</summary>
  public const int BigServerIdFieldNumber = 4;
  private int bigServerId_;
  /// <summary>
  ///大服id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int BigServerId {
    get { return bigServerId_; }
    set {
      bigServerId_ = value;
    }
  }

  /// <summary>Field number for the "SmallServerId" field.</summary>
  public const int SmallServerIdFieldNumber = 5;
  private int smallServerId_;
  /// <summary>
  ///小服id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SmallServerId {
    get { return smallServerId_; }
    set {
      smallServerId_ = value;
    }
  }

  /// <summary>Field number for the "Accountid" field.</summary>
  public const int AccountidFieldNumber = 6;
  private string accountid_ = "";
  /// <summary>
  ///账号id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Accountid {
    get { return accountid_; }
    set {
      accountid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Race" field.</summary>
  public const int RaceFieldNumber = 7;
  private global::GameRace race_ = global::GameRace.None;
  /// <summary>
  ///种族
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::GameRace Race {
    get { return race_; }
    set {
      race_ = value;
    }
  }

  /// <summary>Field number for the "Profession" field.</summary>
  public const int ProfessionFieldNumber = 8;
  private global::GameProfession profession_ = global::GameProfession.None;
  /// <summary>
  ///职业
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::GameProfession Profession {
    get { return profession_; }
    set {
      profession_ = value;
    }
  }

  /// <summary>Field number for the "CursceneId" field.</summary>
  public const int CursceneIdFieldNumber = 9;
  private int cursceneId_;
  /// <summary>
  ///将后面的重新编号
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CursceneId {
    get { return cursceneId_; }
    set {
      cursceneId_ = value;
    }
  }

  /// <summary>Field number for the "BeforeSceneId" field.</summary>
  public const int BeforeSceneIdFieldNumber = 10;
  private int beforeSceneId_;
  /// <summary>
  ///上一个场景id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int BeforeSceneId {
    get { return beforeSceneId_; }
    set {
      beforeSceneId_ = value;
    }
  }

  /// <summary>Field number for the "Pos" field.</summary>
  public const int PosFieldNumber = 11;
  private global::NVector3 pos_;
  /// <summary>
  ///位置
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::NVector3 Pos {
    get { return pos_; }
    set {
      pos_ = value;
    }
  }

  /// <summary>Field number for the "Hp" field.</summary>
  public const int HpFieldNumber = 12;
  private int hp_;
  /// <summary>
  ///血量
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Hp {
    get { return hp_; }
    set {
      hp_ = value;
    }
  }

  /// <summary>Field number for the "Mp" field.</summary>
  public const int MpFieldNumber = 13;
  private int mp_;
  /// <summary>
  ///魔法值
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Mp {
    get { return mp_; }
    set {
      mp_ = value;
    }
  }

  /// <summary>Field number for the "Exp" field.</summary>
  public const int ExpFieldNumber = 14;
  private int exp_;
  /// <summary>
  ///经验
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Exp {
    get { return exp_; }
    set {
      exp_ = value;
    }
  }

  /// <summary>Field number for the "Gold" field.</summary>
  public const int GoldFieldNumber = 15;
  private int gold_;
  /// <summary>
  ///金币
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Gold {
    get { return gold_; }
    set {
      gold_ = value;
    }
  }

  /// <summary>Field number for the "Diamond" field.</summary>
  public const int DiamondFieldNumber = 16;
  private int diamond_;
  /// <summary>
  ///钻石
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Diamond {
    get { return diamond_; }
    set {
      diamond_ = value;
    }
  }

  /// <summary>Field number for the "Dir" field.</summary>
  public const int DirFieldNumber = 17;
  private global::NVector3 dir_;
  /// <summary>
  ///旋转
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::NVector3 Dir {
    get { return dir_; }
    set {
      dir_ = value;
    }
  }

  /// <summary>Field number for the "Speed" field.</summary>
  public const int SpeedFieldNumber = 28;
  private int speed_;
  /// <summary>
  ///速度
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Speed {
    get { return speed_; }
    set {
      speed_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NEntity);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NEntity other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Level != other.Level) return false;
    if (RoleId != other.RoleId) return false;
    if (BigServerId != other.BigServerId) return false;
    if (SmallServerId != other.SmallServerId) return false;
    if (Accountid != other.Accountid) return false;
    if (Race != other.Race) return false;
    if (Profession != other.Profession) return false;
    if (CursceneId != other.CursceneId) return false;
    if (BeforeSceneId != other.BeforeSceneId) return false;
    if (!object.Equals(Pos, other.Pos)) return false;
    if (Hp != other.Hp) return false;
    if (Mp != other.Mp) return false;
    if (Exp != other.Exp) return false;
    if (Gold != other.Gold) return false;
    if (Diamond != other.Diamond) return false;
    if (!object.Equals(Dir, other.Dir)) return false;
    if (Speed != other.Speed) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Level != 0) hash ^= Level.GetHashCode();
    if (RoleId != 0L) hash ^= RoleId.GetHashCode();
    if (BigServerId != 0) hash ^= BigServerId.GetHashCode();
    if (SmallServerId != 0) hash ^= SmallServerId.GetHashCode();
    if (Accountid.Length != 0) hash ^= Accountid.GetHashCode();
    if (Race != global::GameRace.None) hash ^= Race.GetHashCode();
    if (Profession != global::GameProfession.None) hash ^= Profession.GetHashCode();
    if (CursceneId != 0) hash ^= CursceneId.GetHashCode();
    if (BeforeSceneId != 0) hash ^= BeforeSceneId.GetHashCode();
    if (pos_ != null) hash ^= Pos.GetHashCode();
    if (Hp != 0) hash ^= Hp.GetHashCode();
    if (Mp != 0) hash ^= Mp.GetHashCode();
    if (Exp != 0) hash ^= Exp.GetHashCode();
    if (Gold != 0) hash ^= Gold.GetHashCode();
    if (Diamond != 0) hash ^= Diamond.GetHashCode();
    if (dir_ != null) hash ^= Dir.GetHashCode();
    if (Speed != 0) hash ^= Speed.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Level != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Level);
    }
    if (RoleId != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(RoleId);
    }
    if (BigServerId != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(BigServerId);
    }
    if (SmallServerId != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(SmallServerId);
    }
    if (Accountid.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Accountid);
    }
    if (Race != global::GameRace.None) {
      output.WriteRawTag(56);
      output.WriteEnum((int) Race);
    }
    if (Profession != global::GameProfession.None) {
      output.WriteRawTag(64);
      output.WriteEnum((int) Profession);
    }
    if (CursceneId != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(CursceneId);
    }
    if (BeforeSceneId != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(BeforeSceneId);
    }
    if (pos_ != null) {
      output.WriteRawTag(90);
      output.WriteMessage(Pos);
    }
    if (Hp != 0) {
      output.WriteRawTag(96);
      output.WriteInt32(Hp);
    }
    if (Mp != 0) {
      output.WriteRawTag(104);
      output.WriteInt32(Mp);
    }
    if (Exp != 0) {
      output.WriteRawTag(112);
      output.WriteInt32(Exp);
    }
    if (Gold != 0) {
      output.WriteRawTag(120);
      output.WriteInt32(Gold);
    }
    if (Diamond != 0) {
      output.WriteRawTag(128, 1);
      output.WriteInt32(Diamond);
    }
    if (dir_ != null) {
      output.WriteRawTag(138, 1);
      output.WriteMessage(Dir);
    }
    if (Speed != 0) {
      output.WriteRawTag(224, 1);
      output.WriteInt32(Speed);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Level != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Level);
    }
    if (RoleId != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(RoleId);
    }
    if (BigServerId != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(BigServerId);
    }
    if (SmallServerId != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(SmallServerId);
    }
    if (Accountid.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Accountid);
    }
    if (Race != global::GameRace.None) {
      output.WriteRawTag(56);
      output.WriteEnum((int) Race);
    }
    if (Profession != global::GameProfession.None) {
      output.WriteRawTag(64);
      output.WriteEnum((int) Profession);
    }
    if (CursceneId != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(CursceneId);
    }
    if (BeforeSceneId != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(BeforeSceneId);
    }
    if (pos_ != null) {
      output.WriteRawTag(90);
      output.WriteMessage(Pos);
    }
    if (Hp != 0) {
      output.WriteRawTag(96);
      output.WriteInt32(Hp);
    }
    if (Mp != 0) {
      output.WriteRawTag(104);
      output.WriteInt32(Mp);
    }
    if (Exp != 0) {
      output.WriteRawTag(112);
      output.WriteInt32(Exp);
    }
    if (Gold != 0) {
      output.WriteRawTag(120);
      output.WriteInt32(Gold);
    }
    if (Diamond != 0) {
      output.WriteRawTag(128, 1);
      output.WriteInt32(Diamond);
    }
    if (dir_ != null) {
      output.WriteRawTag(138, 1);
      output.WriteMessage(Dir);
    }
    if (Speed != 0) {
      output.WriteRawTag(224, 1);
      output.WriteInt32(Speed);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Level != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
    }
    if (RoleId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(RoleId);
    }
    if (BigServerId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BigServerId);
    }
    if (SmallServerId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SmallServerId);
    }
    if (Accountid.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Accountid);
    }
    if (Race != global::GameRace.None) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Race);
    }
    if (Profession != global::GameProfession.None) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Profession);
    }
    if (CursceneId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CursceneId);
    }
    if (BeforeSceneId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BeforeSceneId);
    }
    if (pos_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
    }
    if (Hp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hp);
    }
    if (Mp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Mp);
    }
    if (Exp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Exp);
    }
    if (Gold != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gold);
    }
    if (Diamond != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Diamond);
    }
    if (dir_ != null) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(Dir);
    }
    if (Speed != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Speed);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NEntity other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Level != 0) {
      Level = other.Level;
    }
    if (other.RoleId != 0L) {
      RoleId = other.RoleId;
    }
    if (other.BigServerId != 0) {
      BigServerId = other.BigServerId;
    }
    if (other.SmallServerId != 0) {
      SmallServerId = other.SmallServerId;
    }
    if (other.Accountid.Length != 0) {
      Accountid = other.Accountid;
    }
    if (other.Race != global::GameRace.None) {
      Race = other.Race;
    }
    if (other.Profession != global::GameProfession.None) {
      Profession = other.Profession;
    }
    if (other.CursceneId != 0) {
      CursceneId = other.CursceneId;
    }
    if (other.BeforeSceneId != 0) {
      BeforeSceneId = other.BeforeSceneId;
    }
    if (other.pos_ != null) {
      if (pos_ == null) {
        Pos = new global::NVector3();
      }
      Pos.MergeFrom(other.Pos);
    }
    if (other.Hp != 0) {
      Hp = other.Hp;
    }
    if (other.Mp != 0) {
      Mp = other.Mp;
    }
    if (other.Exp != 0) {
      Exp = other.Exp;
    }
    if (other.Gold != 0) {
      Gold = other.Gold;
    }
    if (other.Diamond != 0) {
      Diamond = other.Diamond;
    }
    if (other.dir_ != null) {
      if (dir_ == null) {
        Dir = new global::NVector3();
      }
      Dir.MergeFrom(other.Dir);
    }
    if (other.Speed != 0) {
      Speed = other.Speed;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          Level = input.ReadInt32();
          break;
        }
        case 24: {
          RoleId = input.ReadInt64();
          break;
        }
        case 32: {
          BigServerId = input.ReadInt32();
          break;
        }
        case 40: {
          SmallServerId = input.ReadInt32();
          break;
        }
        case 50: {
          Accountid = input.ReadString();
          break;
        }
        case 56: {
          Race = (global::GameRace) input.ReadEnum();
          break;
        }
        case 64: {
          Profession = (global::GameProfession) input.ReadEnum();
          break;
        }
        case 72: {
          CursceneId = input.ReadInt32();
          break;
        }
        case 80: {
          BeforeSceneId = input.ReadInt32();
          break;
        }
        case 90: {
          if (pos_ == null) {
            Pos = new global::NVector3();
          }
          input.ReadMessage(Pos);
          break;
        }
        case 96: {
          Hp = input.ReadInt32();
          break;
        }
        case 104: {
          Mp = input.ReadInt32();
          break;
        }
        case 112: {
          Exp = input.ReadInt32();
          break;
        }
        case 120: {
          Gold = input.ReadInt32();
          break;
        }
        case 128: {
          Diamond = input.ReadInt32();
          break;
        }
        case 138: {
          if (dir_ == null) {
            Dir = new global::NVector3();
          }
          input.ReadMessage(Dir);
          break;
        }
        case 224: {
          Speed = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          Level = input.ReadInt32();
          break;
        }
        case 24: {
          RoleId = input.ReadInt64();
          break;
        }
        case 32: {
          BigServerId = input.ReadInt32();
          break;
        }
        case 40: {
          SmallServerId = input.ReadInt32();
          break;
        }
        case 50: {
          Accountid = input.ReadString();
          break;
        }
        case 56: {
          Race = (global::GameRace) input.ReadEnum();
          break;
        }
        case 64: {
          Profession = (global::GameProfession) input.ReadEnum();
          break;
        }
        case 72: {
          CursceneId = input.ReadInt32();
          break;
        }
        case 80: {
          BeforeSceneId = input.ReadInt32();
          break;
        }
        case 90: {
          if (pos_ == null) {
            Pos = new global::NVector3();
          }
          input.ReadMessage(Pos);
          break;
        }
        case 96: {
          Hp = input.ReadInt32();
          break;
        }
        case 104: {
          Mp = input.ReadInt32();
          break;
        }
        case 112: {
          Exp = input.ReadInt32();
          break;
        }
        case 120: {
          Gold = input.ReadInt32();
          break;
        }
        case 128: {
          Diamond = input.ReadInt32();
          break;
        }
        case 138: {
          if (dir_ == null) {
            Dir = new global::NVector3();
          }
          input.ReadMessage(Dir);
          break;
        }
        case 224: {
          Speed = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class NItem : pb::IMessage<NItem>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NItem> _parser = new pb::MessageParser<NItem>(() => new NItem());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NItem> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::InfoprotoReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NItem() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NItem(NItem other) : this() {
    itemcfgid_ = other.itemcfgid_;
    itemnum_ = other.itemnum_;
    itemid_ = other.itemid_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NItem Clone() {
    return new NItem(this);
  }

  /// <summary>Field number for the "itemcfgid" field.</summary>
  public const int ItemcfgidFieldNumber = 1;
  private long itemcfgid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Itemcfgid {
    get { return itemcfgid_; }
    set {
      itemcfgid_ = value;
    }
  }

  /// <summary>Field number for the "itemnum" field.</summary>
  public const int ItemnumFieldNumber = 2;
  private int itemnum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Itemnum {
    get { return itemnum_; }
    set {
      itemnum_ = value;
    }
  }

  /// <summary>Field number for the "itemid" field.</summary>
  public const int ItemidFieldNumber = 3;
  private int itemid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Itemid {
    get { return itemid_; }
    set {
      itemid_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NItem);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NItem other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Itemcfgid != other.Itemcfgid) return false;
    if (Itemnum != other.Itemnum) return false;
    if (Itemid != other.Itemid) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Itemcfgid != 0L) hash ^= Itemcfgid.GetHashCode();
    if (Itemnum != 0) hash ^= Itemnum.GetHashCode();
    if (Itemid != 0) hash ^= Itemid.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Itemcfgid != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Itemcfgid);
    }
    if (Itemnum != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Itemnum);
    }
    if (Itemid != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Itemid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Itemcfgid != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Itemcfgid);
    }
    if (Itemnum != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Itemnum);
    }
    if (Itemid != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Itemid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Itemcfgid != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Itemcfgid);
    }
    if (Itemnum != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Itemnum);
    }
    if (Itemid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Itemid);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NItem other) {
    if (other == null) {
      return;
    }
    if (other.Itemcfgid != 0L) {
      Itemcfgid = other.Itemcfgid;
    }
    if (other.Itemnum != 0) {
      Itemnum = other.Itemnum;
    }
    if (other.Itemid != 0) {
      Itemid = other.Itemid;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Itemcfgid = input.ReadInt64();
          break;
        }
        case 16: {
          Itemnum = input.ReadInt32();
          break;
        }
        case 24: {
          Itemid = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Itemcfgid = input.ReadInt64();
          break;
        }
        case 16: {
          Itemnum = input.ReadInt32();
          break;
        }
        case 24: {
          Itemid = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
