// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enumproto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from enumproto.proto</summary>
public static partial class EnumprotoReflection {

  #region Descriptor
  /// <summary>File descriptor for enumproto.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EnumprotoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9lbnVtcHJvdG8ucHJvdG8qmwIKDkdhbWVQcm9mZXNzaW9uEhcKE0dhbWVQ",
          "cm9mZXNzaW9uX05vbmUQABIaChZHYW1lUHJvZmVzc2lvbl9XYXJyaW9yEAES",
          "FwoTR2FtZVByb2Zlc3Npb25fTWFnZRACEhkKFUdhbWVQcm9mZXNzaW9uX1By",
          "aWVzdBADEhgKFEdhbWVQcm9mZXNzaW9uX1JvZ3VlEAQSGQoVR2FtZVByb2Zl",
          "c3Npb25fSHVudGVyEAUSGAoUR2FtZVByb2Zlc3Npb25fRHJ1aWQQBhIZChVH",
          "YW1lUHJvZmVzc2lvbl9TaGFtYW4QBxIaChZHYW1lUHJvZmVzc2lvbl9XYXJs",
          "b2NrEAgSGgoWR2FtZVByb2Zlc3Npb25fUGFsYWRpbhAJKj0KCEdhbWVSYWNl",
          "EggKBE5vbmUQABIJCgVIdW1hbhABEgcKA0VsZhACEgcKA09yYxADEgoKBlVu",
          "ZGVhZBAEKiAKB05SZXN1bHQSCwoHU3VjY2VzcxAAEggKBEZhaWwQAWIGcHJv",
          "dG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameProfession), typeof(global::GameRace), typeof(global::NResult), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
///游戏职业
/// </summary>
public enum GameProfession {
  [pbr::OriginalName("GameProfession_None")] None = 0,
  /// <summary>
  ///按照上面的前缀格式重新定义,包括注释
  ///战士
  /// </summary>
  [pbr::OriginalName("GameProfession_Warrior")] Warrior = 1,
  /// <summary>
  ///法师
  /// </summary>
  [pbr::OriginalName("GameProfession_Mage")] Mage = 2,
  /// <summary>
  ///牧师
  /// </summary>
  [pbr::OriginalName("GameProfession_Priest")] Priest = 3,
  /// <summary>
  ///盗贼
  /// </summary>
  [pbr::OriginalName("GameProfession_Rogue")] Rogue = 4,
  /// <summary>
  ///猎人
  /// </summary>
  [pbr::OriginalName("GameProfession_Hunter")] Hunter = 5,
  /// <summary>
  ///德鲁伊
  /// </summary>
  [pbr::OriginalName("GameProfession_Druid")] Druid = 6,
  /// <summary>
  ///萨满
  /// </summary>
  [pbr::OriginalName("GameProfession_Shaman")] Shaman = 7,
  /// <summary>
  ///术士
  /// </summary>
  [pbr::OriginalName("GameProfession_Warlock")] Warlock = 8,
  /// <summary>
  ///圣骑士
  /// </summary>
  [pbr::OriginalName("GameProfession_Paladin")] Paladin = 9,
}

/// <summary>
///游戏种族
/// </summary>
public enum GameRace {
  [pbr::OriginalName("None")] None = 0,
  /// <summary>
  ///人类
  /// </summary>
  [pbr::OriginalName("Human")] Human = 1,
  /// <summary>
  ///精灵
  /// </summary>
  [pbr::OriginalName("Elf")] Elf = 2,
  /// <summary>
  ///兽人
  /// </summary>
  [pbr::OriginalName("Orc")] Orc = 3,
  /// <summary>
  ///亡灵
  /// </summary>
  [pbr::OriginalName("Undead")] Undead = 4,
}

public enum NResult {
  [pbr::OriginalName("Success")] Success = 0,
  [pbr::OriginalName("Fail")] Fail = 1,
}

#endregion


#endregion Designer generated code
